### ISSUE TITLE
local drive?

### ISSUE THREAD

**Issue by DocMAX** [Daniel-Abrecht/fuse-nfs-crossbuild-scripts#3]
i see the drives are mounted as removable drives. is there an option to create local drives?

**Comment by Daniel-Abrecht** [comment]
This is a bit odd, they should be mounted as local drives by default.

You may want to use one of the new `fuse-nfs=dpa` releases (which are my [fork of fuse-nfs](https://github.com/Daniel-Abrecht/fuse-nfs/tree/dpa)), which pass all options not handled by fuse-nfs to fuse directly, which makes all of dokan-fuses options usable: https://github.com/dokan-dev/dokany/blob/5a43c6c6f23d2214480629ef266d3731060634d9/dokan_fuse/src/dokanfuse.cpp#L620-L632
That should allow doing things such as create a removable drive, a network drive, or setting the volume name. If that doesn't help, maybe try using a different drive letter. And if that still doesn't work, I don't know what else could cause this.

**Comment by Daniel-Abrecht** [comment]
I just noticed, it seams it's only a local drive by default since yesterday: https://github.com/dokan-dev/dokany/commit/feeacb527f4a0fe10b1a58cf8e267995751f13c2

Make sure to use a release with `dokany=master`, those should work for this.
